### ISSUE TITLE
find already imported photos by sha1 checksum

### ISSUE THREAD

**Issue by aleneum** [GustavePate/lycheesync#15]
Hello,

let me first thank you for your neat script. It saved me a lot time and trouble and works like a charm!

I have a suggestion:
You could include the checksum in your `photoExists` query in lycheedao at line 145 like that:
```python
    def photoExists(self, photo):
...
            query = ("SELECT * FROM lychee_photos WHERE album='"+ str(photo.albumid) +
                     "' AND (title = '" + photo.originalname + "' OR checksum = '" +
                        str(photo.checksum) + "')")
```
Right now changing the image title in Lychee will cause a reimport of the image with its original name. I googled a bit and it seems that SHA1 should be okay for finding identical photos and collisions are very unlikely.
However, if you change the photo or just save it again, it might change the information storage order (not sure how strict JPG or PNG are) and therefore the hash. In this case, you will have two same looking photos when you've changed the name.
Anyway, using the checksum will improve the accuracy of the function imho :).

What do you think?

Best regards,
Alex

**Comment by GustavePate** [comment]
Hello Alex,

I think your idea is good.

The modified code you write is good enough, I don't think it will add some
evil corner-case ;)
However, photos are not renamed on an everyday basis, in this case a delete
everything before import (-d / -r flag) might just do the trick.

Anyway, I will add this in the next release.

Thanks !

Gustave

**Comment by aleneum** [comment]
Hi Gustave,

you are right. Renaming photos is not a common thing to do.

I just like to make use of the 'title' attribute in lychee and give my images more meaningful titles than "DSC1337.JPG". But since lychee renames all the images to \<sha1# of image\>.\<file extension\> during import, the original file name is lost when I change a picture's title and cannot be used to identify identical images. I'd like to avoid a complete re-import since I all my tagging/naming effort would be gone then. I once tagged more than 5000 pictures in digiKam and lost the progress later. Anything that prevents such a waste of time to happen again is much appreciated :).

So, thank you very much!

Best regards and have a nice week,
Alex
