### ISSUE TITLE
'unicode' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by CarlAmbroselli** [GustavePate/lycheesync#16]
When running `sudo python main.py Fotos lycheesync/conf.json -v -s -l` I get the following error:
ERROR: updating album date for album: XYZ 'unicode' object has no attribute 'strftime'

**Comment by GustavePate** [comment]
Hi Carl, 

Thanks for your bug report.
Could you drop me a bit more logs ?
Maybe there is a more complete stack trace that could help me diagnose the problem ?

Thanks !

**Comment by GustavePate** [comment]
I think I got it ! 
You probably running lycheesync with python3 and it has been written for python2.7 (I will make it compatible in a following release)

Hope this help.
