### ISSUE TITLE
have multible Fotos and Thumbs after Sync

### ISSUE THREAD

**Issue by michaestraub** [GustavePate/lycheesync#17]
Hi, I'm using Lychee at my fotobox, so the guests can watch and download the Fotos on their smartphones. With cron i sync it every Minute with comand: python /var/www/lycheesync/main.py -l   /var/www/lycheesync/foto /var/www /var/www/lycheesync/conf.json
But after a few minutes I have multible thumbs at the gallery. Is there any parameter that awares that?

Thanks a lot
regards Michael

**Comment by GustavePate** [comment]
Hi Michael !

Thanks for the report.

First, running lycheesync every minute is a dangerous idea, even with the -l switch.
It's likely that the script may take longer than one minute to achieve its work, then you will pile up the process which may cause havoc in your photos. Are you sure it's not the case ?

If it's not, please run the script once with the -r flag, everything should be clean after that.
Then launch the script with your standard options and please activate the -v flag for more verbose logs and store them in a file (if you don't know how, append " > /tmp/lycheesync" without the quotes at the end of your command).

If the thumbnail problem strikes again after theses 2 steps, send me the log of the last run.

Hope it will help.

Thanks !

**Comment by michaestraub** [comment]
Thanks, the Time gap is a good hint, I Try that First. I'll let you Know.

Regards michael

Am Mittwoch, 21. Januar 2015 schrieb Gustave Paté :

**Comment by GustavePate** [comment]
Hi Michael,

Some news ? Did you fix your problem ?

Regards,

Gustave

**Comment by michaestraub** [comment]
Hi Gustav,

I have the next gig at Overnext saturday, so I will have a poweruser Test.

Regards Michael

Von meinem iPad gesendet

**Comment by GustavePate** [comment]
Hi Michael,

I think your problem is fix now. Let me know.

Regards,

Gustave

**Comment by michaestraub** [comment]
Hi Gustave,

Thanks for asking yes its better after extend the Timeline but also still
dublicate Fotos in.

Regards Michael

Am Donnerstag, 28. Mai 2015 schrieb Gustave Paté :

> Hi Michael,
>
> I think your problem is fix now. Let me know.
>
> Regards,
>
> Gustave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GustavePate/lycheesync/issues/17#issuecomment-106225575>
> .
>


--

**Comment by GustavePate** [comment]
Hi, thanks for your quick reply.

Have you pull a recent version ?

On 27/10/2014, I added a duplicate check so one lycheesync process could not add duplicate photos (even if the have different names).

There are only two ways to have duplicate now:
- having duplicates in your source folder
- having multiple lycheesync process that process the same photo at exactly the same time

Did you check this two conditions ?

Regards,

Gustave

**Comment by michaestraub** [comment]
Oh that sounds great, I'll check and let you know.

Regards Michael

2015-05-28 10:35 GMT+02:00 Gustave Paté <notifications@github.com>:

> Hi, thanks for your quick reply.
>
> Have you pull a recent version ?
>
> On 27/10/2014, I added a duplicate check so one lycheesync process could
> not add duplicate photos (even if the have different names).
>
> There are only two ways to have duplicate now:
>
>    - having duplicates in your source folder
>    - having multiple lycheesync process that process the same photo at
>    exactly the same time
>
> Did you check this two conditions ?
>
> Regards,
>
> Gustave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GustavePate/lycheesync/issues/17#issuecomment-106232218>
> .
>



--

**Comment by michaestraub** [comment]
Hi Gustave,

now I found the time to look at my Leechesync, is there a command tu update?

regards Michael

2015-05-28 11:05 GMT+02:00 michael straub <mich@elstraub.de>:

> Oh that sounds great, I'll check and let you know.
>
> Regards Michael
>
> 2015-05-28 10:35 GMT+02:00 Gustave Paté <notifications@github.com>:
>
>> Hi, thanks for your quick reply.
>>
>> Have you pull a recent version ?
>>
>> On 27/10/2014, I added a duplicate check so one lycheesync process could
>> not add duplicate photos (even if the have different names).
>>
>> There are only two ways to have duplicate now:
>>
>>    - having duplicates in your source folder
>>    - having multiple lycheesync process that process the same photo at
>>    exactly the same time
>>
>> Did you check this two conditions ?
>>
>> Regards,
>>
>> Gustave
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GustavePate/lycheesync/issues/17#issuecomment-106232218>
>> .
>>
>
>
>
> --
>
>


--

**Comment by michaestraub** [comment]
Hi Gustav,

I updatet with Gut Pull, but still the same, duplicate fotos at Lychee.
crontab
*/3 * * * * python /var/www/lycheesync/main.py -l
/var/www/lycheesync/foto /var/www /var/www/lycheesync/conf.json

THX Michael

2015-07-02 17:10 GMT+02:00 michael straub <mich@elstraub.de>:

> Hi Gustave,
>
> now I found the time to look at my Leechesync, is there a command tu
> update?
>
> regards Michael
>
> 2015-05-28 11:05 GMT+02:00 michael straub <mich@elstraub.de>:
>
>> Oh that sounds great, I'll check and let you know.
>>
>> Regards Michael
>>
>> 2015-05-28 10:35 GMT+02:00 Gustave Paté <notifications@github.com>:
>>
>>> Hi, thanks for your quick reply.
>>>
>>> Have you pull a recent version ?
>>>
>>> On 27/10/2014, I added a duplicate check so one lycheesync process could
>>> not add duplicate photos (even if the have different names).
>>>
>>> There are only two ways to have duplicate now:
>>>
>>>    - having duplicates in your source folder
>>>    - having multiple lycheesync process that process the same photo at
>>>    exactly the same time
>>>
>>> Did you check this two conditions ?
>>>
>>> Regards,
>>>
>>> Gustave
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/GustavePate/lycheesync/issues/17#issuecomment-106232218>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>
>
> --
>
>


--

**Comment by GustavePate** [comment]
Hi Michael,

By default lycheesync won't delete your photos in lychee.
So if duplicates are stored once, the command you run won't delete them.
However, The -d option will delete everything in lychee before importing
photos.

Have you try to:
- comment your crontab
- remove duplicates from lychee (both of them)
- run lycheesyc with your usual options
- check there are no duplicate

?

+ last year questions ;)

>>> There are only two ways to have duplicate now:
>>>
>>> - having duplicates in your source folder
>>> - having multiple lycheesync process that process the same photo at
>>> exactly the same time
>>>
>>> Did you check this two conditions ?

I see, you run lycheesync every 3 minutes, are you sure the process don't
pile up in your os ? Launch:

ls | grep python

There should be only one lycheesync process at any given time.

**Comment by GustavePate** [comment]
old issue + no answer
