### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by denisl-27** [GustavePate/lycheesync#18]
Hi - installed on ubuntu 14.04.  Installed LAMP, Lychee and lycheesync.
When I attempt to import a large number of pictures the import fails.  Seems to work with around 10 or so image imports but large numbers fail.  Thanks for developing this tool this is going to be a great solution with my owncloud setup once it get lycheesync working.  

Not sure if this is important but... I'm using Xpenology as my NFS server which has  "/volume1/users" NFS mounted to my owncloud VM which generates the data and this test Lychee VM.  So owncloud writes to NFS and Lychee is reading the same volume. The directory /home/owncloud is a mount point where I'm NFS mounting my owncloud repository (mount xpenology:/volume1/users /home/owncloud).  

root@TEST-LYCHEE:/home/denisl/lycheesync# python main.py /home/owncloud/data/test /var/www/html/Lychee /home/denisl/lycheesync/conf.json
ERROR could not add IMG_0205.JPG to album subd
Traceback (most recent call last):
  File "/home/denisl/lycheesync/lycheesyncer.py", line 312, in sync
    photo = LycheePhoto(self.conf, f, album)
  File "/home/denisl/lycheesync/lycheemodel.py", line 163, in __init__
    self.exif.taketime = value.split(" ")[1]
IndexError: list index out of range
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Directory scanned: /home/owncloud/data/test
Created albums:  0
29 photos imported on 70 discovered
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by GustavePate** [comment]
Hi Denis,

It's because your photo doesn't have a proper taketime.
I will see what can I do for you in the following week. The script should
not break for such a reason.

Would you mind to send me the img_0205.JPG file that cause the pb so i can
add it to my test suite ? however if you don't want to, because it's
personnal, i will understand.

Have a good day!

Regards,

Gustave

**Comment by denisl-27** [comment]
Hi Gustave,
Thank you for the quick response.
Here is the the picture in the example above - however I do have many pictures that are missing taketime which I suspect got lost in the webdav sync apps I'm using on my IOS devices (trying them all - webdav navigator, photysync, owncloud app).

https://cloud.denisl.com/owncloud/public.php?service=files&t=81f165a76dd372bb6722103ea274f8f8

If there is anything else you need I'm happy to provide any logs / screen shots that may be needed.

Much thanks!
Denis

**Comment by denisl-27** [comment]
Hi Gustave,
Were you able to reproduce the problem with the image I provided?
I greatly appreciate your support on this.  

Thanks

**Comment by GustavePate** [comment]
Hi Denis,

Sorry for the delay, I forgot last time that I wasn't at home the following we.
I just commit something that seems to fix your issue,I have to refactor the whole thing one day ;)

I reproducted the problem with the help of the picture you send me.
Now, your picture is in my test suite and also loaded sucessfully on my lychee test instance.

If you fetch lychee trunk, It should work for you too.
Let me know. 
And feel free to reopen the issue if it doesn't work as expected.

Thanks again for having report this bug.

**Comment by denisl-27** [comment]
Thank you Gustave.  That's great news.
