### ISSUE TITLE
SQL syntax error

### ISSUE THREAD

**Issue by denisl-27** [GustavePate/lycheesync#23]
Hello Gustave,
Received the below error importing a large (5GB) folder of pictures.

root@t-TEST-LYCHEE:/home/lycheesync/lycheesync-master# python main.py /export/nas/owncloud/data/Victoria/files/Pictures/ /var                               /www/html/Lychee/ /home/lycheesync/lycheesync-master/conf.json
createAlbum <type 'exceptions.Exception'>
Traceback (most recent call last):
  File "/home/lycheesync/lycheesync-master/lycheedao.py", line 179, in createAlbum
    cur.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server versio                               n for the right syntax to use near 's','1424124495',0, NULL)' at line 1")
createAlbum <type 'exceptions.Exception'>
Traceback (most recent call last):
  File "/home/lycheesync/lycheesync-master/lycheedao.py", line 179, in createAlbum
    cur.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server versio                               n for the right syntax to use near 'dad birthday 2013','1424124525',0, NULL)' at line 1")

**Comment by denisl-27** [comment]
I've received this error on a few more folders.  I think it's failing when the directory name has an apostrophe.  The actual folder name in the above failure is Denis' dad birthday 2013.

Let me know if this is something you intend on supporting.
In the meantime I can remove all apostrophe's from folder names.

Thanks

**Comment by GustavePate** [comment]
Hi Denis,

I never used lycheesync to manage such a huge collection ;)
It's very likely that you pinpointed the root cause, i don't remeber having
protected the strings.

To be sure, next time activate the -v flag, it will provide some context
(which album, which file) around the error messages.

I will try to upload an apostrophe containing album and image on my test
instance to see if i reproduce the bug.

Thanks for you report !

**Comment by GustavePate** [comment]
I reproducted the bug and just commit a fix.

**Comment by denisl-27** [comment]
Thank you Gustave you're support is truly appreciated. Excellent Lychee add-on.  My wife stores all our photos in a dir/subdir structure on owncloud and I'll setup a cron job to scan the directory structure and import to Lychee.  Very helpful tool.

**Comment by GustavePate** [comment]
Hi denis,

I use lycheesync like you, except i don't synchronize my whole photo
library, only the 5 stars pictures. It's why you should encounter more
corner cases than me.

However, Thank you Denis for sharing your bug reports.
It allow the tool to sharp for you for me and for the community.

See you on next improvement.

Have a good day !
