### ISSUE TITLE
How do I make this work if I don't have command line access?

### ISSUE THREAD

**Issue by 1queer1** [GustavePate/lycheesync#27]
Hi,

I am loving this as a plugin to Lychee- I think it will make Lychee make more sense for some of us with thousands of photos to import.

My question though- is how do I run this without command line access - I don't have terminal access to my servers.

I am not a coder - so I might need very basic explanations. 

Thanks

Dr J

**Comment by GustavePate** [comment]
Hi,

Sorry for you but for the moment, it's a bit technical to use lychee sync
without a shell access on your server.

It will however be possible if you have access:
1. To your remote database from a local shell
2. To your remote lychee directory from a local mountpoint (if you access
your server only with ftp,  try curlftpfs)

The trick is to make lycheesync thinks he is on the server even if you are
on your desktop.

I hope it helps

If your desktop is on windows i won't be able to help but if you're running
linux i may help you in the install process.

Good luck and tell me if you manage to make it work !

**Comment by GustavePate** [comment]
Hi 1queer1,

Did you fixed you problem ? Let me know.

Regards,

Gustave

**Comment by GustavePate** [comment]
old issue + no answer
