### ISSUE TITLE
Keep upcase letters in folder name

### ISSUE THREAD

**Issue by Kernald** [GustavePate/lycheesync#32]
When importing folders, upcase letters are made lowercase. In `lycheesyncer.py`: `album['name'] = "_".join(path).lower()`

Is there a technical reason to lowercase the full name?

**Comment by GustavePate** [comment]
Hi !

No technical reason that I can remember.
As I said to Tynan made the same request 2 days ago by email (maybe it's you), I will take care of this in a few days.

Thank you for opening this issue.

Regards,

**Comment by Kernald** [comment]
Well it's not me, but thanks for planning to take care of that!

**Comment by GustavePate** [comment]
Sorry for the delay, not a lot of time theses days so I tested the fix very quickly.
Tell me if it works for you (no release associated with this fix just git pull the trunk).

Regards,

**Comment by Kernald** [comment]
Works fine, thanks!

**Comment by GustavePate** [comment]
You are welcome.
And thanks for this message (and the issue report !)
Le 30 août 2015 23:38, "Marc Plano-Lesay" <notifications@github.com> a
écrit :
