### ISSUE TITLE
ValueError: Invalid control character 

### ISSUE THREAD

**Issue by SeanyP321** [GustavePate/lycheesync#34]
Hi there,

I'm entirely new to all this and using OS X so things are even less straight forward. I think I've got python/Mysql etc sorted as well as the additional prerequisites. 

When I run: python main.py /Volumes/Photo\ and\ Video\ Archive\ 1/Photos /Applications/MAMP/htdocs/Lychee-master /Users/appleharddrive/lycheesync/conf.json

I get the following:

Traceback (most recent call last):
  File "main.py", line 81, in <module>
    conf_data = json.load(conf_file)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 2 column 30 (char 31)

Any input on what I'm doing wrong would be greatly appreciated. This isn't something I can google!

Thanks

**Comment by GustavePate** [comment]
Hi Seany,

Thank your for openning this issue !

Clearly, you have an " Invalid control character at: line 2 column 30 (char
31)" in your
/Users/appleharddrive/lycheesync/conf.json file.

Given the column number and expecting that you wrote valid json in your
file, i guess that column 30 is the last of this line. Am i right ?

If it's the last character, I don't kreally know what the python version
for macosx intend to be a valid control character but it will likely expect
to have a crlf as an end of line and not just a cr (tell me if I talk
chinese to you ;) )

It may be your problem...

So a few questions for you, if you want me to help further:

Are you sure you wrote valid json in your conf.json ?
Is the char 31 the last of your line 2 ?
Do you know if it's a CR or a CRLF ?

I hope this will help you,

Regards,

Gustave

**Comment by GustavePate** [comment]
Hi Seany,

Did you fix your problem ?

**Comment by GustavePate** [comment]
No response. Closed.
