### ISSUE TITLE
take date of Nikon D7000 photos is wrong

### ISSUE THREAD

**Issue by ronnyhartenstein** [GustavePate/lycheesync#37]
With my D7000 test JPG the tags from PIL are this:

    DateTimeOriginal 2014:01:12 13:58:55
    DateTimeDigitized 2014:01:12 13:58:55
    DateTime 2015:03:15 07:59:19

So using `DateTime` here ist wrong, it should be using the `DateTimeOriginal` if it exists.

**Comment by GustavePate** [comment]
Thank you Ronny !

I don't have much time right now but will merge your PR as soon has I have a little time to pass my regression test.

Thanks again, you rock !

Regards,

Gustave
