### ISSUE TITLE
can't get plugin running

### ISSUE THREAD

**Issue by Segdon** [GustavePate/lycheesync#39]
Hello,
after a lot of reading - i'm not a programmer - i got the plugin running.
I was wondering, do i have to run this plugin manually every time, or is there a way to let this happen automaticly?

**Comment by GustavePate** [comment]
Hi Segdon,

Sorry for the late reply.
You just have to use [crontab](https://help.ubuntu.com/community/CronHowto) and let the system launch the script for you on a regular basis.

Regards,

Gustave
