### ISSUE TITLE
Ordering of photos in albums

### ISSUE THREAD

**Issue by jamesfcarter** [GustavePate/lycheesync#40]
Hi,

At the moment photos appear in the album in whatever order os.walk supplies them in. I'd like to have them in date order. As a quick hack I've just ordered them by filename which is close enough.

```
--- a/lycheesyncer.py
+++ b/lycheesyncer.py
@@ -344,7 +344,7 @@ class LycheeSyncer:
                     self.deleteFiles(filelist)
 
                 # Albums are created or emptied, now take care of photos
-                for f in files:
+                for f in sorted(files):
                     if self.isAPhoto(f):
 
                         try:
```

**Comment by GustavePate** [comment]
Hi James !

Thanks for your bug report.
I will definitely add this to the next version.

Regards,

Gustave

**Comment by GustavePate** [comment]
OK, committed in next release branch
