### ISSUE TITLE
Script incompatible with Windows OS?

### ISSUE THREAD

**Issue by coopak** [GustavePate/lycheesync#41]
The User & Group variables import credentials via the Unix-only pwd & grp modules. Forgive my ignorance, but is there a way to add support for Windows so that the script can access the Lychee database?

**Comment by GustavePate** [comment]
Hi coopak, 

Really I don't know (there should be one, a "if sytem.isUnix() souhld exists in python")
But I'm not a windows user and don't want to be one ;)

If you manage to make lycheesync work on windows and submit me a Pull Request that doesn't break my regression test, I will integrate your changes.

Regards,

Gustave
