### ISSUE TITLE
Removal of individual Photos

### ISSUE THREAD

**Issue by palitu** [GustavePate/lycheesync#47]
I am syncing about 30'000 photos into Lychee, using a year - Month format to my folders.

I have a bunch of photos that will be deleted, but i do not want to have to do a full sync, just remove the ones that are missing.

could this be handled by the syncer?

**Comment by GustavePate** [comment]
Hi Palitu !

I'm not sure to fully understand your feature request.

> I have a bunch of photos that will be deleted,

Why, by whom (by lychee's UI ? by you in the source folder lycheesync use ?)
I guess it's the second option...

> but i do not want to have to do a full sync, just remove the ones that are missing.

I understand that:

you have sync Lychee and your source folder using Lycheesync.
you delete some photos in the source folder.
Then, you launch lycheesync
You want these deleted photos to disappear from Lychee without having to reimport all the others

Am I right ?

If I am, there's indeed no way to do that actually.
And, I agree with you,  it's a good feature to add !

**Comment by palitu** [comment]
Yes, you have the process correct.  I guess it would require LS building an
index of files then comparing it to Lychee and deleting the ones that are
no longer available.

cheers

**Comment by nomisge** [comment]
In the case of link-mode this would be very simple.
Find all orphaned symlinks, and delete them from db by url field...

I'm trying to use lycheesync in junction with owncloud on one machine. Hence link-mode. Deleting a file in owncloud leaves orphaned symlinks. I'd like to delete those together with db entry.

In lychedao a procedure removeFileFromAlbum( self, photo ) would be needed (simple sql delete statement)
An extra script could then simply scan fro symlinks and delete them from db..

Should I look into this myself, or is this planned soon anyway?

**Comment by palitu** [comment]
that is exaclty (well almost) my use case!

I dump files into an unsorted fodler, run the "SortPhotos" script (from
github), then symlink with lycheesync.

I don't think Gustave has it planned, it would be great if you could look
into it!

cheers,

**Comment by GustavePate** [comment]
I could add an option for a quick sanity test at the end of the script without a pb.
- check if lychee's db file exists in lychee directory
- if yes and file is link, check if it's an orphan

It's winter, I will add this on a rainy day ;)

**Comment by palitu** [comment]
thanks Gustave!

**Comment by GustavePate** [comment]
Fixed [here](https://github.com/GustavePate/lycheesync/blob/master/lycheesync/lycheesyncer.py#L462)

Will check every photo in db and see if it exists in lychee's fs, if not remove it from db.
Then will check every photo in lychee's fs and will remove it if it doesn't exists in db.
DB and FS will be sync at the sanity check end's.
