### ISSUE TITLE
Exclude specific folder by name

### ISSUE THREAD

**Issue by giafrata** [GustavePate/lycheesync#53]
Hi, thanks for this great job, it's exactly what I was looking for a long time. I've just a little feature request, maybe it will be easily implemented and can help someone else to enjoy better your work.. 
If I've photos stored in some folders like a NAS or similar file sharing system ( Samba etc ) it's very likely that some hidden folders as `.Thumbnails` was created by client and synced in Lychee as an unwanted album.. can be added a configuration field in json or a parameter to pass in lycheesync call that contains a comma separated list of strings (or something else) that represent exact folder names to be skipped during sync? 
Thanks!

**Comment by GustavePate** [comment]
Hi giafrata !

Great feature idea thank you for poisting it.
I will definitely implement it.

**Comment by giafrata** [comment]
Thank you @GustavePate ! :smile:
