### ISSUE TITLE
Syncing fails to create albums due to duplicate primary key

### ISSUE THREAD

**Issue by therealdealneil** [GustavePate/lycheesync#55]
When syncing albums, the following error message is displayed when the script tries to create new albums.  The message displays for every album.

`pymysql.err.IntegrityError: (1062, "Duplicate entry '0' for key 'PRIMARY'")
ERROR;2016-04-03 10:39:50,706; lycheesync.lycheedao; createAlbum: Dinner Party - Dec 2012 -> {'id': None, 'relpath': 'Dinner Party - Dec 2012', 'photos': [], 'name': 'Dinner Party - Dec 2012', 'path': '/media/Pictures/Dinner Party - Dec 2012'}
ERROR;2016-04-03 10:39:50,707; lycheesync.lycheesyncer; didn't manage to create album for: Dinner Party - Dec 2012
ERROR;2016-04-03 10:39:50,708; lycheesync.lycheedao; (1062, "Duplicate entry '0' for key 'PRIMARY'")`

Poking around the source shows lychee doesn't have an auto-incrementing primary key.  It instead [generates an ID](https://github.com/electerious/Lychee/php/helpers/generateID.php) based on the time in microseconds.  I modified the lycheesync code to generate an ID in this manner when creating an album and it creates the album.  I'm not sure if this is the best fix for this however.

**Comment by GustavePate** [comment]
Hi Neil, 

I just saw your message I was away for a fee days.

Did you have this error each time you launched lycheesync or was it a matter of bad luck.
The id for albums is not timestamp based (just an auto increment). I'd really like to reproduce your problem. Have you tried with the -v option which is a little bit more verbose.

Let me know,

Gustave

**Comment by tribut** [comment]
I have the same problem. Seems like  @therealdealneil is right - this is the commit which introduced the id generation: https://github.com/electerious/Lychee/commit/976635254e3eb8d2333e9e66760234ea24571b80.

**Comment by rom1dep** [comment]
the fix backported from https://github.com/tribut/lycheesync/commit/19023d1e1e9fc5f536b08396cd68cc4369f9f75e works for me.

**Comment by iamsebastian** [comment]
Same here: https://github.com/tribut/lycheesync/commit/19023d1e1e9fc5f536b08396cd68cc4369f9f75e fixed it
