### ISSUE TITLE
WARNING : model date impossible to parse: 2007-00-00 00:00:00

### ISSUE THREAD

**Issue by geodatup** [GustavePate/lycheesync#78]
after syncing, I get a

 `WARNING :  lycheesync.lycheemodel; model date impossible to parse: 2007-00-00 00:00:00
`
or 
 `WARNING :  lycheesync.lycheemodel; model date impossible to parse: 2048-03-13 13:46:38`
what does it mean ?

**Comment by GustavePate** [comment]
Hi hugo,

it only means that your photo exif tag for the date is invalid, it's only a
warning your photo should be visible in lychee.

Regards
